### PR TITLE
Issue 123

### PR DESCRIPTION
**Pull request by elodieburtin**

### CODE REVIEW

**Comment by FServais** [comment]
👍👍

Can we also hide the button to delete a board game from the board game's list? :)

**Comment by elodieburtin** [comment]
I hesitated and decided against it: the delete button is only shown for the board games that the current user added, so the situation in which the delete button is visible should only occur if the user joined the event, added some board games, then left the event (not possible in the UI as far as I know). And in such a situation, shouldn't the user have the possibility to remove his/her board games? But I think the backend does not allow it, so, I'd like your opinion (and those of other componions) on that!

**Comment by FServais** [comment]
That is very true...!

I was rather thinking of the case when the event is finished or "closed". Then no modification of state should be allowed IMO.

@waliens BTW, any side effect on removing a board game from an event? If games were already created for instance.

**Comment by waliens** [comment]
@FServais It shouldn't be an issue. The game are linked to the board games and not specifically to the board games brought to an event. 
 
I am not sure about the use case of removing a board game after leaving an event (is it realistic i mean ?). I would say either it shouldn't be possible to remove the board games after leaving (because games were brought so it is great to keep them in the list for the records), or they should be deleted automatically when someone leaves an event. Note that there is currently a workaround which consists in re-joining the event, deleting the board games and then leaving again (which is not possible from the UI indeed).

**Comment by FServais** [comment]
This is a very specific case... I would argue we should keep it consistent with backend that does not allow it. But really, it's ok for me to leave it :)

**Comment by elodieburtin** [comment]
I agree on the fact that it is better to keep the board games in the list for records, but if we allow users to remove the board games while they are still on the event, the behaviour should be consistent. Automatically deleting the board games from the event when a user leaves it seems better for me. Another possibility would be to prevent a user to leave the event if some of his/her board games are still present. Anyway, since the UI does not currently allow such a situation, I think we can leave it like that for now and discuss it again if/when needed

**Pull request merged**
